import {
  IconVisualizationColumn16,
  IconVisualizationLine16,
  IconVisualizationScatter16,
  IconVisualizationBar16,
  IconVisualizationArea16,
  IconVisualizationPie16,
  IconVisualizationColumnStacked16,
  IconVisualizationBarStacked16,
  IconVisualizationGauge16,
  IconVisualizationRadar16,
  IconVisualizationPivotTable16,
  IconWorld16,
  IconLocation16,
} from '@dhis2/ui';
export const VISUALIZATION_TYPES = [
  {
    type: 'COLUMN',
    description: 'Column',
    label: 'Column',
    icon: IconVisualizationColumn16,
  },
  {
    type: 'STACKED_COLUMN',
    description: 'Stacked Column',
    label: 'Stacked Column',
    icon: IconVisualizationColumnStacked16,
  },
  {
    type: 'BAR',
    description: 'Bar',
    label: 'Bar',
    icon: IconVisualizationBar16,
  },
  {
    type: 'STACKED_BAR',
    description: 'Stacked Bar',
    label: 'Stacked Bar',
    icon: IconVisualizationBarStacked16,
  },
  {
    type: 'LINE',
    description: 'Line',
    label: 'Line',
    icon: IconVisualizationLine16,
  },
  {
    type: 'DOTTED',
    description: 'Dotted',
    label: 'Dotted',
    icon: IconVisualizationScatter16,
  },
  {
    type: 'AREA',
    description: 'Area',
    label: 'Area',
    icon: IconVisualizationArea16,
  },
  {
    type: 'PIE',
    description: 'Pie',
    label: 'Pie',
    icon: IconVisualizationPie16,
  },
  {
    type: 'SOLIDGAUGE',
    description: 'Gauge',
    label: 'Gauge',
    icon: IconVisualizationGauge16,
  },
  {
    type: 'RADAR',
    description: 'Radar',
    label: 'Radar',
    icon: IconVisualizationRadar16,
  },
  {
    type: 'PIVOT_TABLE',
    description: 'Pivot Table',
    label: 'Pivot Table',
    icon: IconVisualizationPivotTable16,
  },
  {
    type: 'MAP',
    description: 'Map',
    icon: IconWorld16,
    label: 'Map',
    hiddenInList: true,
  },
  {
    type: 'TRACKED_ENTITY_LAYER',
    description: 'Tracked entity layer',
    icon: IconLocation16,
    label: 'Layer',
    hiddenInList: true,
  },
];
