export type FieldControlType =
  | 'dropdown'
  | 'multi-dropdown'
  | 'textbox'
  | 'textarea'
  | 'checkbox'
  | 'date'
  | 'date-time'
  | 'image'
  | 'org-unit'
  | 'file'
  | 'boolean'
  | 'number'
  | 'tel'
  | 'transfer'
  | 'coordinate'
  | 'search';
